// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolvePrismaDatasourceUrls } from "./src/lib/database-url";

const datasource = (() => {
  try {
    const urls = resolvePrismaDatasourceUrls(process.env);
    return {
      url: urls.url,
      ...(urls.directUrl ? { directUrl: urls.directUrl } : {}),
    };
  } catch {
    return { url: process.env["DATABASE_URL"] };
  }
})();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource,
});
